---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hero
  labels:
    app: hero
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: hero
  template:
    metadata:
      labels:
        app: hero
    spec:
      containers:
      - name: hero
        image: workshop/hero:latest
        ports:
        - name: http
          containerPort: 8080
        imagePullPolicy: IfNotPresent
        env:
          - name: QUARKUS_DATASOURCE_URL
            valueFrom:
              configMapKeyRef:
                name: supes-config
                key: database
          - name: QUARKUS_DATASOURCE_USERNAME
            valueFrom:
              secretKeyRef:
                name: supes-database-secret
                key: username
          - name: QUARKUS_DATASOURCE_PASSWORD
            valueFrom:
              secretKeyRef:
                name: supes-database-secret
                key: password